# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5eb35dc458b57ee68de7e946781b2b6267019f0a2d44ddd4dc06e1bae9becef00ba96c0296886512ee60f011f1d0043bcf42e7f95fefabf2520d9fe54411445

test:
  secret_key_base: ad0b287564e454025ab139fe5950307ecfcd620f49f607a5d6a52e2f90fd37ebce3b0cc3bce432c5aa3fc7b0d525124511c54f0db8deff6559e0f2ce22bb0840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
